### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by Almuperez** [Almuperez/princess-snake-project#1]
Hola,

Como tengo alguna duda con el README aprovecho para poner en práctica labels, projects, milestone
Dudas referentes a que tipo de librería utilizar, todavía no consigo saber cuáll podría usar o si usare varias.
Por otro lado no sé si el README para este jueves sirve simplemente con poner un poco de que tratará el juego.

**Comment by amargopastor** [comment]
@Almuperez cualquier cosa ya sabes ! :)
