### ISSUE TITLE
Confusion generacion coronas

### ISSUE THREAD

**Issue by Almuperez** [Almuperez/princess-snake-project#10]
**Describe the bug**
Problema en la generación del actor corona. 

1. Tengo dudas sobre lo que me ha comentado Marcos de usar la librería lodash, no se si le he entendido bien. ¿tengo que llevar acabo un array de coronas con al librería lodash?

2. Por intentar ir pintando las coronas he duplicado el archivo snake como también hemos comentado pero mi sorpresa es que cuando se lo paso al script no me lo devuelve en la consola :( ¿debería pintar aunque sea la serpiente de nuevo no?

**To Reproduce**
Los archivos dónde podéis ver a lo que me refiero son script.ts y crown.ts
Tengo otro archivo crown2ts. pero este no es al que me refiero

**Expected behavior**
Espera generar otra serpiente y de ahí volver a al forma del cuadrado, pintarla de rosa y pasar al array de actores en el archivo script cuatro nuevos crown.

Gracias!!!!

**Comment by Almuperez** [comment]
Holaaaa!!! he conseguido que se vea la corona, era un error básico!! me faltaba pasarle crown a actors en la función render para poder pintar 🥳🥳🥳 sigo con el resto de coronas!!! @amargopastor te pedí tutoría para hoy porque estaba desesperada, pero me gustaría seguir teniéndola pero revisar un poco todo lo que llevo, además ahora empezaré con colisión y va ser una colisión para mi cerebro!

**Comment by amargopastor** [comment]
@Almuperez estupendo! Nos vemos de tarde. Sigue así! 🚀 🚀 🚀
