### ISSUE TITLE
Problemas con colision

### ISSUE THREAD

**Issue by Almuperez** [Almuperez/princess-snake-project#12]
**Describe the bug**
Encuentro dos problemas con la colisión en los que estoy trabajando:

1. Archivo Crown.ta: Cuando le paso el actor snake al actor Crown para poder generar la función del update de dos objetos acercándose, el array de coronas creado en  scripts me da error con el mensaje “se esperaban 3 argumentos pero se obtuvieron 0”

2. Por otro lado, en  la función update dentro de Crown cuando  intento hacer la formula de dos objetos se acerca me dice que la posición de sanePos es indefinida, creo que tiene algo que ver con la posición que le he dado a la serpiente en script… pero estoy investigando

**To Reproduce**
Lo que indico arriba se puede ver en los archivos:
- crown.ts
- script.ts
El archivo gamemanager de momento esta ok.

**Expected behavior**
El comportamiento que estaba esperando era el acercamiento de snake a crown y cuando esto se produjera, cambiar el color de crown. Una vez consiguiera esto mi objetivo era intentar hacer desaparecer crown.

**Comment by amargopastor** [comment]
Hello @Almuperez !

Como comentamos ayer no es a Crown.ts a quien debes pasar snake. Crown.ts solamente pinta una corona con su posición y, llegado el caso, deja de pintar o cambia su posición.

Es en singleton de ManagerGame quién recibe tu objeto snake y el que genera un array de coronas. Al disponer de toda la información de manera centralizada desde este archivo puedes hacer todas las comprobaciones necesarias para la colisión.

Es exactamente igual al fichero CircuitManager. De echo me sorprende un poco esta issue ya que ayer en nuestra tutoría lo dejamos todo listo para trabajar en tu propio ManagerGame.ts 🤔 🤔 🤔

**Comment by Almuperez** [comment]
Hola Marcos,

Siii en canvas car si se pasa car al archivo barrier que es mi crown!!!
Para cambiar de colores las barreras con touch! En un primer momento pensé
que te lo acabarías llevando todo a lo que sería mi gamemaster… pero mire
los archivos de clase y esa parte sigue en barrier.

De todas formas si no me llevo todo a game a ver si desde ahí me sale. Solo
quería que supieras porque lo he hecho así !!!

Graciasss

**Comment by amargopastor** [comment]
@Almuperez efectivamente, barrier recibe car por el interés en su posición. Eso es correcto. Puedes implementarlo así según lo visto en clase.

Pide una tutoría hoy antes de la macro-tutoría de las 18.00 y le echamos un vistazo
