### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Almuperez** [Almuperez/princess-snake-project#2]
Terminar de crear todo el contenido que llevará mi README

**Comment by Almuperez** [comment]
Nunca había usado markdown para generar archivos md por lo que me ha llevado más tiempo del que esperaba, aún continuo trabajando en darle la forma deseada.

**Comment by amargopastor** [comment]
@Almuperez sigue así! lo bueno es que una vez que domines markdown la documentación de todos tus proyectos será un cañón! 💪 💪 💪
