### ISSUE TITLE
Instalación paquetes

### ISSUE THREAD

**Issue by Almuperez** [Almuperez/princess-snake-project#4]
**Describe the bug**
Al instalarme tsconfig se me ha generado una dependencia en el packa.json y no se me genera el archivo de siempre. No sé si como estoy trabajando con yarn es normal o he cometido algún error. El comando utilizado fue `yarn add tsconfig.json`

Tampoco se me ha generado el archivo de siempre package.json.lock

**To Reproduce**
1. Go to 'package.json'
2. Click on 'package.json'
3. Scroll down to 'line 12 devDependencies'
4. See error 'no es un error, pero no se porque se ha generado ahí'

**Expected behavior**
Esperaba que se generá el archivo tsconfig con toda la ifnormación de siempre

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 11.5.2

**Comment by amargopastor** [comment]
@Almuperez aquí tienes un lío grande. ¿Cuándo hemos ejecutado en clase `yarn add tsconfig.json`?

yarn add es para añadir paquetes de npm a nuestro proyecto. Si quieres trabajar con tipescript los pasos son:

```bash
yarn add typescript
yarn run tsc --init
```

**Comment by Almuperez** [comment]
Por supuesto tengo un lío grande, si no no hago la issue para pedir ayuda…. Pero gracias por la aclaración
