### ISSUE TITLE
[Report] 27/12/2021

### ISSUE THREAD

**Issue by Almuperez** [Almuperez/princess-snake-project#6]
**Issues que hoy voy a llevar a cabo**

1. -Revisar código de clase para ver dónde puedo apoyarme: 

- Archivo barrier.ts para coger como base y hacer la corona. En lugar de cambiar de color cambiarán de posición: pendiente saber como hacer.
- Archivo pacman.ts para conseguir movimiento serpiente: pendiente como hacer

2. Dibujar un cuadrado en Canvas que terminará siendo la serpiente: ok
3. Dibujar un cuadrado en Canvas que terminará siendo la corna: ok
4. Generar actor serpiente: en proceso

**Por hacer**

1. Generar actor corona
2. Dar movimiento a serpiente
3. Dar movimiento a corona

**Recursos usados en el día de hoy**
- tutoria Alvaro: revisión de instalación de paquetes y tsconfig. Recvision de cuadrado.
-documentación https://developer.mozilla.org/es/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes
https://developer.mozilla.org/es/docs/Web/API/Canvas_API
- https://codepen.io/hippostar/pen/QgWXxe

**Comment by amargopastor** [comment]
Excelente @Almuperez ! Sigue así! 🚀 🚀 🚀
